
spring:
  session:
    store-type: redis

  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mystest?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 8
      max-wait: 8
      max-idle: 0
      min-idle: 0
server:
  address: localhost
  port: 8089
  tomcat:
    uri-encoding: utf-8



