
spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mystest
    username: root
    password: 123456
server:
  address: localhost
  port: 8089
  tomcat:
    uri-encoding: utf-8



